# Generated by Django 6.0 on 2026-03-20 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('version_tag', models.CharField(max_length=32)),
                ('code_blob', models.TextField(help_text='Python可执行代码')),
                ('entry_point', models.CharField(default='main', help_text='入口函数', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='gateway.tool')),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gateway.toolversion'),
        ),
        migrations.CreateModel(
            name='ExecutionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('arguments_json', models.TextField(default='{}')),
                ('status', models.CharField(choices=[('PENDING', '待分配'), ('RUNNING', '执行中'), ('DONE', '成功完成'), ('FAILED', '执行失败')], default='PENDING', max_length=16)),
                ('executor_id', models.CharField(blank=True, max_length=64, null=True)),
                ('result_json', models.TextField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.toolversion')),
            ],
        ),
    ]
