# Generated by Django 6.0 on 2026-03-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='input_schema',
            field=models.JSONField(blank=True, default=dict, help_text='JSON Schema for the tool inputs'),
        ),
    ]
